# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#######################################################################################
# Jekyll site settings
title: Principles and Techniques of Data Science
author: Sam Lau, Joey Gonzalez, and Deborah Nolan
email: samlau@berkeley.edu
description: >-
  This is the textbook for Data 100, the Principles and Techniques of Data
  Science course at UC Berkeley.

  Data 100 is the upper-division, semester-long data science course that
  follows Data 8, the Foundations of Data Science. The reader’s assumed
  background is detailed in the About This Book page.

  The contents of this book are licensed for free consumption under the
  following license: Creative Commons Attribution-NonCommercial-NoDerivatives
  4.0 International (CC BY-NC-ND 4.0)

baseurl: ""
url: ""

#######################################################################################
# Jupyter Book settings

# Main page settings
footer_text: ~

# Sidebar settings
show_sidebar: true # Show the sidebar. Only set to false if your only wish to host a single page.
collapse_inactive_chapters: true # Whether to collapse the inactive chapters in the sidebar
textbook_logo: ~
textbook_logo_link: ~
sidebar_footer_text:
  Powered by <a href="https://github.com/jupyter/jupyter-book">Jupyter
  Book</a>
number_toc_chapters: true # Whether to add numbers to chapters in your Table of Contents. If true, you can control this at the Chapter level in _data/toc.yml

# Search settings
search_max_words_in_content: 100 # In the search function, use at most this many words (too many words will make search slow)

#######################################################################################
# Interact link settings

# General interact settings
use_jupyterlab: false # If 'true', interact links will use JupyterLab as the interface

# Jupyterhub link settings
use_jupyterhub_button: false # If 'true', display a button that will direct users to a JupyterHub (that you provide)
jupyterhub_url: "" # The URL for your JupyterHub. If no URL, use ""
jupyterhub_interact_text: Interact # The text that interact buttons will contain.

# Binder link settings
use_binder_button: false # If 'true', add a binder button for interactive links
binderhub_url: https://mybinder.org # The URL for your BinderHub. If no URL, use ""
binder_repo_base: https://github.com/ # The site on which the textbook repository is hosted
binder_repo_org: DS-100 # The username or organization that owns this repository
binder_repo_name: textbook # The name of the repository on the web
binder_repo_branch: master # The branch on which your textbook is hosted.
binderhub_interact_text: Interact # The text that interact buttons will contain.

# Thebelab settings
use_thebelab_button: false # If 'true', display a button to allow in-page running code cells with Thebelab
thebelab_button_text: Thebelab # The text to display inside the Thebelab initialization button
codemirror_theme: abcdef # Theme for codemirror cells, for options see https://codemirror.net/doc/manual.html#config

# nbinteract settings
use_show_widgets_button: true # If 'true', display a button to allow in-page running code cells with nbinteract

# Download settings
use_download_button: true # If 'true', display a button to download a zip file for the notebook
download_button_text: Download # The text that download buttons will contain

#######################################################################################
# Jupyter book extensions and additional features

# Bibliography and citation settings. See https://github.com/inukshuk/jekyll-scholar#configuration for options
scholar:
  style: apa

#######################################################################################
# Option to add a Goggle analytics tracking code

# Navigate to https://analytics.google.com, add a new property for your jupyter book and copy the tracking id here.
google_analytics:
  mytrackingcode: UA-113006011-1

#######################################################################################
# Jupyter book settings you probably don't need to change

content_folder_name: content # The folder where your raw content (notebooks/markdown files) are located
images_url: /assets/images # Path to static image files
css_url: /assets/css # Path to static CSS files
js_url: /assets/js # Path to JS files
custom_static_url: /assets/custom # Path to user's custom CSS/JS files

#######################################################################################
# Jekyll build settings (only modify if you know what you're doing)

# Site settings
defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
      toc_label: "  On this page"
      toc_icon: list-ul
      excerpt: ""

favicon_path: images/logo/favicon.ico

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

permalink: /:categories/:year/:month/:day/:title

collections:
  build:
    output: true
    permalink: /:path.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - content/
  - .sass-cache/

plugins:
  - jekyll-redirect-from

# Jupyter Book version - DO NOT CHANGE THIS. It is generated when a new book is created
jupyter_book_version: 0.5.3dev0
