#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: Learning Data Science # The title of the book. Will be placed in the left navbar.
author: Sam Lau, Joey Gonzalez, and Deb Nolan # The author of the book
copyright: "2023" # Copyright year to be placed in the footer

# Never execute notebooks automatically so we don't get unexpected book changes
execute:
  execute_notebooks: "off"

only_build_toc_files: true
exclude_patterns: [old_pages/*]

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
  myst_url_schemes: [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links

html:
  extra_footer: |
    <p>
    License: CC BY-NC-ND 4.0
    </p>
  google_analytics_id: UA-113006011-1
  home_page_in_navbar: false

launch_buttons:
  jupyterhub_url: https://datahub.berkeley.edu
  binderhub_url: ''
  # binderhub_url: https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe: false

repository:
  url: https://github.com/ds-100/textbook  # The URL to your book's repository
  path_to_book: content
  branch: master  # Which branch of the repository should be used when creating links

# bibtex_bibfiles:
#   - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_extra_path: ['datasets']

    # this is commented out since we aren't supporting interactive plotly plots
    # right now, but if we want to support that in the future be sure to
    # uncomment out the code here and in custom.js.
    # html_js_files:
    # - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js

  extra_extensions:
    - sphinx_multitoc_numbering
