#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: Principles and Techniques of Data Science # The title of the book. Will be placed in the left navbar.
author: Sam Lau, Joey Gonzalez, and Deb Nolan # The author of the book
copyright: "2020" # Copyright year to be placed in the footer

# Never execute notebooks automatically so we don't get unexpected book changes
execute:
  execute_notebooks: "off"

html:
  extra_footer: |
    <p>
    License: CC BY-NC-ND 4.0
    </p>
  google_analytics_id: UA-113006011-1
  home_page_in_navbar: false

launch_buttons:
  thebe: false
